users:
  julianbs:
    tier: tier2
    groups: [ARC1, ARC2]
    home: /home/julianbs
    symlink: /OneDrive/ARC2.CVDInstitute

  hanif:
    tier: tier1
    groups: [ARC1]
    home: /home/hanif
    symlink: /OneDrive/ARC1.HealthSystemInstitute

  nilakshi:
    tier: tier3
    groups: [ARC3]
    home: /home/nilakshi
    symlink: /OneDrive/ARC3.ChildHealthInstitute
