users:
  julianbs:
    password: julianpw
    tier: tier2
    home: /home/julianbs
    projects:
      - base: "ARC8. Global Surgery Institute"
        folders:
          - "8.1 Workforce"
          - "8.2 Volume"
          - "8.3 Timely Access"

  hanif:
    password: hanifpw
    tier: tier1
    home: /home/hanif
    projects:
      - base: "ARC8. Global Surgery Institute"
        folders:
          - "8.1 Workforce"
          - "8.3 Timely Access"

  nilakshi:
    password: nilakshipw
    tier: tier3
    home: /home/nilakshi
    projects:
      - base: "ARC8. Global Surgery Institute"
        folders:
          - "8.2 Volume"
